# Generated by Django 4.1.13 on 2024-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0002_colaborador_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
